// Package head_digit_of_operation_id provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/gerhardwagner/oapi-codegen version v1.15.0 DO NOT EDIT.
package head_digit_of_operation_id
