// Package headdigitofhttpheader provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/gerhardwagner/oapi-codegen version v1.15.0 DO NOT EDIT.
package headdigitofhttpheader

type N200ResponseHeaders struct {
	N000Foo string
}
type N200Response struct {
	Headers N200ResponseHeaders
}
